conv_layers:
  - out_channels: 32
    kernel_size: 3
  - out_channels: 64
    kernel_size: 3
  - out_channels: 128
    kernel_size: 3
  - out_channels: 256
    kernel_size: 3
  - out_channels: 512
    kernel_size: 3
dense_layers:
  - 512
  - 256
  - 128
input_shape: ${transforms.resize}

