defaults:
  - model: basic
  - transforms: basic

training:
  batch_size: 32
  epochs: 10
  learning_rate: 0.001
  train_dir: 'data/train'
  val_dirs: ['data/val']

logging:
  steps: 10

run_name: pd-${now:%Y-%m-%d-%H-%M}
